# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Chauve
email: mtmgang@gmail.com
instagram_username: chauvvee
youtube_username: celiox23
real:
  - id: 3iZWuvAQjlg
  - id: 5BoThOKVKaE
  - id: ZC6gq-yYRfA
address:
  - line: a cote de panam
  - line:
  # Feel free to add more lines here
telephone: +336 00 00 00 00
copyright:

# Build settings
markdown: kramdown
